apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes-app
  template:
    metadata:
      labels:
        app: hello-kubernetes-app
    spec:
      containers:
      - name: hello-kubernetes-app
        image: lh0ss/hello-kubernetes-app:v1
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001